# Generated by Django 5.1.2 on 2024-11-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
